[tool.poetry]
name = "tdmctl"
version = "0.1.2"
description = "command line tool client for TouDoum-Framework"
authors = ["msterhuj <gabin.lanore@gmail.com>"]
homepage = "https://toudoum-framework.github.io/"
documentation = "https://toudoum-framework.github.io/tdmctl/"
repository = "https://github.com/TouDoum-Framework/tdmctl"
readme = "README.md"
keywords = ["toudoum", "framework", "cli", "client", "tool", "tdmctl", "management"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
] # https://pypi.org/classifiers/

[tool.poetry.scripts]
tdmctl = "tdmctl.main:app"

[tool.poetry.dependencies]
python = "^3.8"
columnar = "^1.4.1"
colorama = "^0.4.5"
typer = {extras = ["all"], version = "^0.6.1"}
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
