[tool.poetry]
name = "cybergenetics"
version = "0.0.3"
description = "Cybergenetics is a controlled simulating environment for chemical reaction networks (CRNs) and co-cultures."
authors = ["Yi Zhang, Quentin Badolle"]
license = "BSD 3-Clause"

[tool.poetry.dependencies]
python = "^3.7"
gym = "^0.25.0"
torch = "^1.12.0"
seaborn = "^0.11.2"
imageio = "^2.20.0"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
