[tool.poetry]
name = "mctinctools"
version = "0.1.3"
description = "Common tools for our organization."
authors = ["forums34 <greg.wendel@hey.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/forums34/mctinctools"
repository = "https://github.com/forums34/mctinctools.git"
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^7.1.2"
python-dotenv = "^0.20.0"
rich = "^12.5.1"
Jinja2 = "^3.1.2"
pandas = "^1.4.3"
click = "^8.1.3"
mkdocstrings = "^0.19.0"
mdx-gh-links = "^0.3"
Faker = "^13.15.1"
mkdocstrings-python = "^0.7.1"
mkdocs-material = "^8.3.9"
mkdocs-gen-files = "^0.3.5"
mkdocs-literate-nav = "^0.4.1"
pre-commit = "^2.20.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
scriv = {extras = ["toml"], version = "^0.16.0"}
nox = "^2022.1.7"
Faker = "^13.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
