[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "dsphere"
version = "0.0.6"
authors = [
  { name="Example Author", email="author@example.com" },
]
description = "An example package"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
dependencies = [
    "pandas",
    "numpy",
    "matplotlib",
    "dask",
    "pyarrow",
    "scikit-learn==1.0.0",
    "scipy >= 1.4.0, <1.9.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]