[project]
name = "ogimg"
dynamic = []
description = "A Python CLI for downloading metadata images (e.g., OG images) from web pages."
authors = [
    { name = "JoÃ£o Palmeiro", email = "joaopalmeiro@proton.me" },
]
dependencies = [
    "metadata-parser>=0.10.5",
    "click>=8.1.3",
]
requires-python = ">=3.7"
readme = "README.md"
version = "0.1.1"

[project.license]
text = "MIT"

[project.scripts]
ogimg = "ogimg.cli:main"

[project.urls]
Repository = "https://github.com/joaopalmeiro/ogimg"
Homepage = "https://github.com/joaopalmeiro/ogimg"

[project.optional-dependencies]

[tool.pdm.version]
source = "file"
path = "src/ogimg/__init__.py"

[tool.pdm.dev-dependencies]
format = [
    "black>=22.6.0",
    "isort>=5.10.1",
]

[tool.black]
line-length = 88
target-version = [
    "py37",
]

[tool.isort]
profile = "black"
atomic = true

[build-system]
requires = [
    "pdm-pep517>=1.0.0",
]
build-backend = "pdm.pep517.api"
