[tool.poetry]
name = "dagster_fmt"
version = "0.0.1"
description = "Dagster code gen tool"
authors = ["arudolph <alex3rudolph@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
isort = "^5.10.1"
black = "^22.6.0"
pytest = "^7.1.2"
pre-commit = "^2.20.0"
astpretty = "^3.0.0"
dagster = "^0.15.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
