[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "sdif-toolkit"
version = "0.0.2"
authors = [
  { name="Colin Mothersead", email="cmothersead@gmail.com" },
]
description = "Utility to read and process swimming data files"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cmothersead/sdif-reader"
"Bug Tracker" = "https://github.com/cmothersead/sdif-reader/issues"