[project]
name = "grid_run"
version = "0.2"
authors = [
  { name="Ruixiang JIANG", email="1138561926@qq.com" },
]
description = "A simple tool for executing and managing shell commands"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/songrise/GridRun"
"Bug Tracker" = "https://github.com/songrise/GridRun/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"