[tool.poetry]
name = "xdisplayselect"
version = "0.1.1"
description = "Utility to simplify controlling monitors on linux WMs"
authors = ["ItsDrike <itsdrike@protonmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/ItsDrike/xdisplayselect"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = ">3.9,<4"
inquirer = "^2.10.0"

[tool.poetry.dev-dependencies]
poetry-dynamic-versioning = {version = "^0.17.1", optional = true}
flake8 = "^4.0.1"
flake8-annotations = "^2.9.0"
flake8-bugbear = "^22.7.1"
flake8-future-annotations = "^0.0.5"
flake8-pep585 = {version = "^0.1.5", python = ">=3.9"}
flake8-simplify = "^0.19.2"
flake8-tidy-imports = "^4.8.0"
pep8-naming = "^0.12.1"
black = "^22.3.0"
isort = "^5.10.1"
pyright = "^1.1.264"
pre-commit = "^2.18.1"
taskipy = "^1.10.2"

[tool.poetry.scripts]
xdisplayselect = 'xdisplayselect.__main__:main'


[tool.black]
line-length = 119
extend-exclude = "^/.cache"

[tool.isort]
profile = "black"
line_length = 119
atomic = true
order_by_type = false
case_sensitive = true
combine_as_imports = true
skip = [".venv", ".git", ".cache"]

[tool.taskipy.tasks]
precommit = "pre-commit install"
lint = "pre-commit run --all-files"
black = "black ."
isort = "isort ."
pyright = "pyright ."
flake8 = "flake8 ."

[tool.poetry-dynamic-versioning]
enable = true
bump = true
vcs = "git"
style = "pep440"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
